@page "/patients"
@inject HttpClient HttpClient
@using System.Text.Json
@using System.Net
@using VModel

<h3>Liste des patients</h3>

@if (listePatients != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Date de Naissance</th>
                <th>Genre</th>
                <th>Adresse</th>
                <th>Téléphone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var patient in listePatients)
            {
                <tr>
                    <td>@patient.Id</td>
                    <td>@patient.Prenom</td>
                    <td>@patient.Nom</td>
                    <td>@patient.DateNaissance</td>
                    <td>@patient.Genre</td>
                    <td>@patient.AdressePostale</td>
                    <td>@patient.Telephone</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p><tr>Aucun patient trouvé.</tr>
        @errorMessage
    </p>
}

@code {
    public  List<PatientVM>? listePatients;
    private string? errorMessage;

    protected override async Task OnInitializedAsync()
    {
        try
        {
            using var handler = new HttpClientHandler();
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            handler.ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) =>
            {
                return true;
            };

            using var client = new HttpClient(handler);
            //listePatients = await client.GetFromJsonAsync<List<PatientVM>>("http://back_Patient:8080/API/Patient/");

            //pour passer par le gateway il faudrait faire la ligne ci-dessous, mais il repasse en HTTPS et dans ce cas j'ai un problème de certificat.
            listePatients = await client.GetFromJsonAsync<List<PatientVM>>("https://ApiGateway:5011/API/patient-back/");

        }
        catch (HttpRequestException ex)
        {

            errorMessage = "Une erreur s'est produite lors de la récupération des patients : " + ex.Message+"\n"+ex.StackTrace;
        }
    }  
}